model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    conditioning_key: crossattn
    cond_stage_key: cond_img
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema
    parameterization: "eps"
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 128

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "/data/engs2456/server_stuff/latent-diffusion/logs/2023-01-15T16-05-24_autoencoder_kl_64x64x3_heart/checkpoints/epoch=000006.ckpt"
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 224
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.Feats_Embedder
      # .ClassEmbedder
      params:
          
          key: 'cond_img'
          
          



data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.heartdata_feats.HeartData
      params:
        dfp : "heartdata/train_df_without_situs.csv"
        image_size: [224,224]
        data_len: 5000
    validation:
      target: ldm.data.heartdata_feats.HeartData
      
      params:
        dfp : "heartdata/valid_df_without_situs.csv"
        image_size: [224,224]
        data_len: 500


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 300
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
